name: Update Local Folder
on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest changes from remote repository
        run: |
          git fetch origin
          git reset --hard origin/main
